services:
  - type: web
    name: shbox-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /api/messages
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: DatabaseProvider
        value: Postgres
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: shbox-db
          property: connectionString

databases:
  - name: shbox-db
    plan: free
    databaseName: shbox
    user: shbox
